### ISSUE TITLE
Flytte resultatene på top

### ISSUE THREAD

**Issue by sfabriece** [webstep-or/hackathon2016#2]
Jeg tenker at det er lurt å flytte resultatene på toppen av kartet istedet for under.

**Comment by webstep-or** [comment]
Hei! Sjekk pages branchen. Har fiksa litt på det. Fremdeles ikke helt smooth da men. Holder på med litt angående å ta med 5 rundt jobb også. Må skrive om endel da det er mye async callbacks..

**Comment by sfabriece** [comment]
kult, si ifra hvis det er noe som må gjøres. Gjerne lage små issues per gjøremål så kan vi plukke og fikse. Tenker åpen source modelen.

**Comment by webstep-or** [comment]
Jeg kan godt legge inn et par. Bare vent til jeg får sjekka inn den endringen jeg holder på med. Den er ganske stor. Stay tuned
